apiVersion: batch/v1
kind: CronJob
metadata:
  name: osv-ingester
spec:
  concurrencyPolicy: Forbid
  schedule: "*/15 * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 30
      backoffLimit: 3
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: osv-ingester
            image: osv-ingester:latest
            imagePullPolicy: IfNotPresent
            command:
            - ./application
            - gcs
            env:
              - name: DB_REDIS_HOST
                valueFrom:
                  secretKeyRef:
                    name: exhort-onguard-secret
                    key: db.host
              - name: DB_REDIS_PORT
                valueFrom:
                  secretKeyRef:
                    name: exhort-onguard-secret
                    key: db.port
            resources:
              limits:
                cpu: 300m
                memory: 1000Mi
              requests:
                cpu: 100m
                memory: 500Mi